addSbtPlugin("io.spray"             % "sbt-revolver"        % "0.9.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.typesafe"         % "sbt-mima-plugin"     % "0.6.0")
addSbtPlugin("com.github.gseitz"    % "sbt-release"         % "1.0.11")
addCompilerPlugin("org.scalamacros" % "paradise"            % "2.1.1" cross CrossVersion.full)
